# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analyse_dialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AnalyseDialog(object):
    def setupUi(self, AnalyseDialog):
        AnalyseDialog.setObjectName("AnalyseDialog")
        AnalyseDialog.resize(791, 641)
        self.analyse = QtWidgets.QWidget(AnalyseDialog)
        self.analyse.setGeometry(QtCore.QRect(10, 120, 771, 511))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.analyse.setFont(font)
        self.analyse.setAutoFillBackground(True)
        self.analyse.setObjectName("analyse")
        self.btn_selectDecError = QtWidgets.QPushButton(AnalyseDialog)
        self.btn_selectDecError.setGeometry(QtCore.QRect(20, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_selectDecError.setFont(font)
        self.btn_selectDecError.setObjectName("btn_selectDecError")
        self.btn_selectRaError = QtWidgets.QPushButton(AnalyseDialog)
        self.btn_selectRaError.setGeometry(QtCore.QRect(140, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_selectRaError.setFont(font)
        self.btn_selectRaError.setObjectName("btn_selectRaError")
        self.btn_selectDecErrorAltitude = QtWidgets.QPushButton(AnalyseDialog)
        self.btn_selectDecErrorAltitude.setGeometry(QtCore.QRect(260, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_selectDecErrorAltitude.setFont(font)
        self.btn_selectDecErrorAltitude.setObjectName("btn_selectDecErrorAltitude")
        self.btn_selectRaErrorAltitude = QtWidgets.QPushButton(AnalyseDialog)
        self.btn_selectRaErrorAltitude.setGeometry(QtCore.QRect(380, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_selectRaErrorAltitude.setFont(font)
        self.btn_selectRaErrorAltitude.setObjectName("btn_selectRaErrorAltitude")
        self.btn_selectModelPointPolar = QtWidgets.QPushButton(AnalyseDialog)
        self.btn_selectModelPointPolar.setGeometry(QtCore.QRect(500, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_selectModelPointPolar.setFont(font)
        self.btn_selectModelPointPolar.setObjectName("btn_selectModelPointPolar")
        self.btn_selectDecErrorAzimuth = QtWidgets.QPushButton(AnalyseDialog)
        self.btn_selectDecErrorAzimuth.setGeometry(QtCore.QRect(260, 60, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_selectDecErrorAzimuth.setFont(font)
        self.btn_selectDecErrorAzimuth.setObjectName("btn_selectDecErrorAzimuth")
        self.btn_selectModelPointErrorPolar = QtWidgets.QPushButton(AnalyseDialog)
        self.btn_selectModelPointErrorPolar.setGeometry(QtCore.QRect(500, 60, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_selectModelPointErrorPolar.setFont(font)
        self.btn_selectModelPointErrorPolar.setObjectName("btn_selectModelPointErrorPolar")
        self.btn_selectRaErrorDeviation = QtWidgets.QPushButton(AnalyseDialog)
        self.btn_selectRaErrorDeviation.setGeometry(QtCore.QRect(140, 60, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_selectRaErrorDeviation.setFont(font)
        self.btn_selectRaErrorDeviation.setObjectName("btn_selectRaErrorDeviation")
        self.btn_selectRaErrorAzimuth = QtWidgets.QPushButton(AnalyseDialog)
        self.btn_selectRaErrorAzimuth.setGeometry(QtCore.QRect(380, 60, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_selectRaErrorAzimuth.setFont(font)
        self.btn_selectRaErrorAzimuth.setObjectName("btn_selectRaErrorAzimuth")
        self.btn_selectDecErrorDeviation = QtWidgets.QPushButton(AnalyseDialog)
        self.btn_selectDecErrorDeviation.setGeometry(QtCore.QRect(20, 60, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_selectDecErrorDeviation.setFont(font)
        self.btn_selectDecErrorDeviation.setObjectName("btn_selectDecErrorDeviation")
        self.analyseBackground = QtWidgets.QLabel(AnalyseDialog)
        self.analyseBackground.setGeometry(QtCore.QRect(0, 0, 790, 111))
        self.analyseBackground.setText("")
        self.analyseBackground.setObjectName("analyseBackground")
        self.analyseBackground.raise_()
        self.btn_selectDecError.raise_()
        self.btn_selectRaError.raise_()
        self.btn_selectDecErrorAltitude.raise_()
        self.btn_selectRaErrorAltitude.raise_()
        self.btn_selectModelPointPolar.raise_()
        self.btn_selectDecErrorAzimuth.raise_()
        self.btn_selectModelPointErrorPolar.raise_()
        self.btn_selectRaErrorDeviation.raise_()
        self.btn_selectRaErrorAzimuth.raise_()
        self.btn_selectDecErrorDeviation.raise_()
        self.analyse.raise_()

        self.retranslateUi(AnalyseDialog)
        QtCore.QMetaObject.connectSlotsByName(AnalyseDialog)

    def retranslateUi(self, AnalyseDialog):
        _translate = QtCore.QCoreApplication.translate
        AnalyseDialog.setWindowTitle(_translate("AnalyseDialog", "Analyse"))
        self.btn_selectDecError.setToolTip(_translate("AnalyseDialog", "<html><head/><body><p>Show Dec Error in arc sec from modeling file</p></body></html>"))
        self.btn_selectDecError.setText(_translate("AnalyseDialog", "Dec Error"))
        self.btn_selectRaError.setToolTip(_translate("AnalyseDialog", "<html><head/><body><p>Show Ra Error in arc sec from modeling file.</p></body></html>"))
        self.btn_selectRaError.setText(_translate("AnalyseDialog", "Ra Error"))
        self.btn_selectDecErrorAltitude.setToolTip(_translate("AnalyseDialog", "<html><head/><body><p>Show Dec Error in arc sec from modeling file over Altitude.</p></body></html>"))
        self.btn_selectDecErrorAltitude.setText(_translate("AnalyseDialog", "Dec Error over Alt"))
        self.btn_selectRaErrorAltitude.setToolTip(_translate("AnalyseDialog", "<html><head/><body><p>Show Ra Error in arc sec from modeling file over Altitude.</p></body></html>"))
        self.btn_selectRaErrorAltitude.setText(_translate("AnalyseDialog", "Ra Error over Alt"))
        self.btn_selectModelPointPolar.setToolTip(_translate("AnalyseDialog", "<html><head/><body><p>Show model points in colors over altitude and azimuth in polar diagram. blue: points west, green: points east.</p></body></html>"))
        self.btn_selectModelPointPolar.setText(_translate("AnalyseDialog", "Model Points Polar"))
        self.btn_selectDecErrorAzimuth.setToolTip(_translate("AnalyseDialog", "<html><head/><body><p>Show Dec Error in arc sec from modeling file over Azimuth.</p></body></html>"))
        self.btn_selectDecErrorAzimuth.setText(_translate("AnalyseDialog", "Dec Error over Az"))
        self.btn_selectModelPointErrorPolar.setToolTip(_translate("AnalyseDialog", "<html><head/><body><p>Show total error in colors over altitude and azimuth in polar diagram. blue: points west, green: points east.</p></body></html>"))
        self.btn_selectModelPointErrorPolar.setText(_translate("AnalyseDialog", "Model Error Polar"))
        self.btn_selectRaErrorDeviation.setToolTip(_translate("AnalyseDialog", "<html><head/><body><p>Show Ra Error in arc sec from modeling file with respect to the first model point.</p></body></html>"))
        self.btn_selectRaErrorDeviation.setText(_translate("AnalyseDialog", "RA Error Flexure"))
        self.btn_selectRaErrorAzimuth.setToolTip(_translate("AnalyseDialog", "<html><head/><body><p>Show Ra Error in arc sec from modeling file over Azimuth.</p></body></html>"))
        self.btn_selectRaErrorAzimuth.setText(_translate("AnalyseDialog", "Ra Error over Az"))
        self.btn_selectDecErrorDeviation.setToolTip(_translate("AnalyseDialog", "<html><head/><body><p>Show Dec Error in arc sec from modeling file with respect to the first model point.</p></body></html>"))
        self.btn_selectDecErrorDeviation.setText(_translate("AnalyseDialog", "DEC Error Flexure"))

