# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analyse_window_ui.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AnalyseDialog(object):
    def setupUi(self, AnalyseDialog):
        AnalyseDialog.setObjectName("AnalyseDialog")
        AnalyseDialog.resize(791, 641)
        self.analyse = QtWidgets.QWidget(AnalyseDialog)
        self.analyse.setGeometry(QtCore.QRect(10, 115, 771, 516))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.analyse.setFont(font)
        self.analyse.setAutoFillBackground(True)
        self.analyse.setObjectName("analyse")
        self.btn_errorTime = QtWidgets.QPushButton(AnalyseDialog)
        self.btn_errorTime.setGeometry(QtCore.QRect(140, 15, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_errorTime.setFont(font)
        self.btn_errorTime.setObjectName("btn_errorTime")
        self.btn_errorOverview = QtWidgets.QPushButton(AnalyseDialog)
        self.btn_errorOverview.setGeometry(QtCore.QRect(20, 15, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_errorOverview.setFont(font)
        self.btn_errorOverview.setObjectName("btn_errorOverview")
        self.analyseBackground = QtWidgets.QLabel(AnalyseDialog)
        self.analyseBackground.setGeometry(QtCore.QRect(0, 0, 790, 106))
        self.analyseBackground.setText("")
        self.analyseBackground.setObjectName("analyseBackground")
        self.btn_errorAzAlt = QtWidgets.QPushButton(AnalyseDialog)
        self.btn_errorAzAlt.setGeometry(QtCore.QRect(260, 15, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_errorAzAlt.setFont(font)
        self.btn_errorAzAlt.setObjectName("btn_errorAzAlt")
        self.checkWinsorize = QtWidgets.QCheckBox(AnalyseDialog)
        self.checkWinsorize.setGeometry(QtCore.QRect(535, 15, 111, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkWinsorize.setFont(font)
        self.checkWinsorize.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkWinsorize.setChecked(False)
        self.checkWinsorize.setObjectName("checkWinsorize")
        self.winsorizeLimit = QtWidgets.QDoubleSpinBox(AnalyseDialog)
        self.winsorizeLimit.setGeometry(QtCore.QRect(730, 15, 41, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.winsorizeLimit.setFont(font)
        self.winsorizeLimit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.winsorizeLimit.setDecimals(0)
        self.winsorizeLimit.setMinimum(1.0)
        self.winsorizeLimit.setMaximum(30.0)
        self.winsorizeLimit.setSingleStep(1.0)
        self.winsorizeLimit.setProperty("value", 5.0)
        self.winsorizeLimit.setObjectName("winsorizeLimit")
        self.label_201 = QtWidgets.QLabel(AnalyseDialog)
        self.label_201.setGeometry(QtCore.QRect(665, 15, 61, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_201.setFont(font)
        self.label_201.setObjectName("label_201")
        self.checkOptimized = QtWidgets.QCheckBox(AnalyseDialog)
        self.checkOptimized.setGeometry(QtCore.QRect(535, 50, 196, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkOptimized.setFont(font)
        self.checkOptimized.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkOptimized.setChecked(False)
        self.checkOptimized.setObjectName("checkOptimized")
        self.analyseBackground.raise_()
        self.btn_errorTime.raise_()
        self.btn_errorOverview.raise_()
        self.analyse.raise_()
        self.btn_errorAzAlt.raise_()
        self.checkWinsorize.raise_()
        self.winsorizeLimit.raise_()
        self.label_201.raise_()
        self.checkOptimized.raise_()

        self.retranslateUi(AnalyseDialog)
        QtCore.QMetaObject.connectSlotsByName(AnalyseDialog)

    def retranslateUi(self, AnalyseDialog):
        _translate = QtCore.QCoreApplication.translate
        AnalyseDialog.setWindowTitle(_translate("AnalyseDialog", "Analyse"))
        self.btn_errorTime.setToolTip(_translate("AnalyseDialog", "<html><head/><body><p>Shows the Ra Dec error of the aligment model from data.</p></body></html>"))
        self.btn_errorTime.setText(_translate("AnalyseDialog", "Error over time"))
        self.btn_errorOverview.setToolTip(_translate("AnalyseDialog", "<html><head/><body><p>Shows an overview of the aligment model error from data.</p></body></html>"))
        self.btn_errorOverview.setText(_translate("AnalyseDialog", "Error overview"))
        self.analyseBackground.setProperty("color", _translate("AnalyseDialog", "blue"))
        self.btn_errorAzAlt.setToolTip(_translate("AnalyseDialog", "<html><head/><body><p>Shows the Az Alt error of the aligment model from data.</p></body></html>"))
        self.btn_errorAzAlt.setText(_translate("AnalyseDialog", "Error over Az/Alt"))
        self.checkWinsorize.setToolTip(_translate("AnalyseDialog", "<html><head/><body><p>Cuts outlayers by using winsorize method with the given limit.</p></body></html>"))
        self.checkWinsorize.setText(_translate("AnalyseDialog", "Winsorize data"))
        self.winsorizeLimit.setToolTip(_translate("AnalyseDialog", "<html><head/><body><p><br/></p></body></html>"))
        self.label_201.setText(_translate("AnalyseDialog", "Limit in %"))
        self.checkOptimized.setToolTip(_translate("AnalyseDialog", "<html><head/><body><p>Cuts outlayers by using winsorize method with the given limit.</p></body></html>"))
        self.checkOptimized.setText(_translate("AnalyseDialog", "Use data with pointing model"))

