# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hemisphere_dialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HemisphereDialog(object):
    def setupUi(self, HemisphereDialog):
        HemisphereDialog.setObjectName("HemisphereDialog")
        HemisphereDialog.resize(791, 641)
        font = QtGui.QFont()
        font.setFamily("Arial")
        HemisphereDialog.setFont(font)
        self.hemisphere = QtWidgets.QWidget(HemisphereDialog)
        self.hemisphere.setEnabled(True)
        self.hemisphere.setGeometry(QtCore.QRect(10, 105, 771, 526))
        self.hemisphere.setAutoFillBackground(True)
        self.hemisphere.setStyleSheet("")
        self.hemisphere.setObjectName("hemisphere")
        self.btn_deletePoints = QtWidgets.QPushButton(HemisphereDialog)
        self.btn_deletePoints.setGeometry(QtCore.QRect(20, 10, 111, 36))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_deletePoints.setFont(font)
        self.btn_deletePoints.setObjectName("btn_deletePoints")
        self.hemisphereBackground = QtWidgets.QLabel(HemisphereDialog)
        self.hemisphereBackground.setGeometry(QtCore.QRect(0, 0, 790, 96))
        self.hemisphereBackground.setText("")
        self.hemisphereBackground.setObjectName("hemisphereBackground")
        self.groupBox_2 = QtWidgets.QGroupBox(HemisphereDialog)
        self.groupBox_2.setGeometry(QtCore.QRect(150, 10, 161, 76))
        self.groupBox_2.setObjectName("groupBox_2")
        self.btn_editNone = QtWidgets.QRadioButton(self.groupBox_2)
        self.btn_editNone.setGeometry(QtCore.QRect(50, 10, 106, 21))
        self.btn_editNone.setChecked(True)
        self.btn_editNone.setObjectName("btn_editNone")
        self.btn_editModelPoints = QtWidgets.QRadioButton(self.groupBox_2)
        self.btn_editModelPoints.setGeometry(QtCore.QRect(50, 30, 106, 21))
        self.btn_editModelPoints.setObjectName("btn_editModelPoints")
        self.btn_editHorizonMask = QtWidgets.QRadioButton(self.groupBox_2)
        self.btn_editHorizonMask.setGeometry(QtCore.QRect(50, 50, 106, 21))
        self.btn_editHorizonMask.setObjectName("btn_editHorizonMask")
        self.bar_numberPointsProcessed = QtWidgets.QProgressBar(HemisphereDialog)
        self.bar_numberPointsProcessed.setGeometry(QtCore.QRect(570, 70, 201, 16))
        self.bar_numberPointsProcessed.setMaximum(1000)
        self.bar_numberPointsProcessed.setProperty("value", 1)
        self.bar_numberPointsProcessed.setTextVisible(False)
        self.bar_numberPointsProcessed.setObjectName("bar_numberPointsProcessed")
        self.le_numberPointsProcessed = QtWidgets.QLineEdit(HemisphereDialog)
        self.le_numberPointsProcessed.setGeometry(QtCore.QRect(545, 70, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.le_numberPointsProcessed.setFont(font)
        self.le_numberPointsProcessed.setMouseTracking(False)
        self.le_numberPointsProcessed.setFocusPolicy(QtCore.Qt.NoFocus)
        self.le_numberPointsProcessed.setAcceptDrops(False)
        self.le_numberPointsProcessed.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.le_numberPointsProcessed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_numberPointsProcessed.setReadOnly(True)
        self.le_numberPointsProcessed.setObjectName("le_numberPointsProcessed")
        self.label_81 = QtWidgets.QLabel(HemisphereDialog)
        self.label_81.setGeometry(QtCore.QRect(480, 70, 66, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_81.setFont(font)
        self.label_81.setObjectName("label_81")
        self.bar_numberPointsSolved = QtWidgets.QProgressBar(HemisphereDialog)
        self.bar_numberPointsSolved.setGeometry(QtCore.QRect(570, 50, 201, 16))
        self.bar_numberPointsSolved.setMaximum(1000)
        self.bar_numberPointsSolved.setProperty("value", 1)
        self.bar_numberPointsSolved.setTextVisible(False)
        self.bar_numberPointsSolved.setObjectName("bar_numberPointsSolved")
        self.le_numberPointsSolved = QtWidgets.QLineEdit(HemisphereDialog)
        self.le_numberPointsSolved.setGeometry(QtCore.QRect(545, 50, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.le_numberPointsSolved.setFont(font)
        self.le_numberPointsSolved.setMouseTracking(False)
        self.le_numberPointsSolved.setFocusPolicy(QtCore.Qt.NoFocus)
        self.le_numberPointsSolved.setAcceptDrops(False)
        self.le_numberPointsSolved.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.le_numberPointsSolved.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_numberPointsSolved.setReadOnly(True)
        self.le_numberPointsSolved.setObjectName("le_numberPointsSolved")
        self.label_28 = QtWidgets.QLabel(HemisphereDialog)
        self.label_28.setGeometry(QtCore.QRect(480, 50, 66, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.bar_numberPointsImaged = QtWidgets.QProgressBar(HemisphereDialog)
        self.bar_numberPointsImaged.setGeometry(QtCore.QRect(570, 30, 201, 16))
        self.bar_numberPointsImaged.setMaximum(1000)
        self.bar_numberPointsImaged.setProperty("value", 1)
        self.bar_numberPointsImaged.setTextVisible(False)
        self.bar_numberPointsImaged.setObjectName("bar_numberPointsImaged")
        self.le_numberPointsImaged = QtWidgets.QLineEdit(HemisphereDialog)
        self.le_numberPointsImaged.setGeometry(QtCore.QRect(545, 30, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.le_numberPointsImaged.setFont(font)
        self.le_numberPointsImaged.setMouseTracking(False)
        self.le_numberPointsImaged.setFocusPolicy(QtCore.Qt.NoFocus)
        self.le_numberPointsImaged.setAcceptDrops(False)
        self.le_numberPointsImaged.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.le_numberPointsImaged.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_numberPointsImaged.setReadOnly(True)
        self.le_numberPointsImaged.setObjectName("le_numberPointsImaged")
        self.label_77 = QtWidgets.QLabel(HemisphereDialog)
        self.label_77.setGeometry(QtCore.QRect(480, 30, 66, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_77.setFont(font)
        self.label_77.setObjectName("label_77")
        self.bar_numberPointsSlewed = QtWidgets.QProgressBar(HemisphereDialog)
        self.bar_numberPointsSlewed.setGeometry(QtCore.QRect(570, 10, 201, 16))
        self.bar_numberPointsSlewed.setMaximum(1000)
        self.bar_numberPointsSlewed.setProperty("value", 1)
        self.bar_numberPointsSlewed.setTextVisible(False)
        self.bar_numberPointsSlewed.setObjectName("bar_numberPointsSlewed")
        self.le_numberPointsSlewed = QtWidgets.QLineEdit(HemisphereDialog)
        self.le_numberPointsSlewed.setGeometry(QtCore.QRect(545, 10, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.le_numberPointsSlewed.setFont(font)
        self.le_numberPointsSlewed.setMouseTracking(False)
        self.le_numberPointsSlewed.setFocusPolicy(QtCore.Qt.NoFocus)
        self.le_numberPointsSlewed.setAcceptDrops(False)
        self.le_numberPointsSlewed.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.le_numberPointsSlewed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_numberPointsSlewed.setReadOnly(True)
        self.le_numberPointsSlewed.setObjectName("le_numberPointsSlewed")
        self.label_100 = QtWidgets.QLabel(HemisphereDialog)
        self.label_100.setGeometry(QtCore.QRect(480, 10, 66, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_100.setFont(font)
        self.label_100.setObjectName("label_100")
        self.le_numberPointsToModel = QtWidgets.QLineEdit(HemisphereDialog)
        self.le_numberPointsToModel.setGeometry(QtCore.QRect(435, 30, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.le_numberPointsToModel.setFont(font)
        self.le_numberPointsToModel.setMouseTracking(False)
        self.le_numberPointsToModel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.le_numberPointsToModel.setAcceptDrops(False)
        self.le_numberPointsToModel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.le_numberPointsToModel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_numberPointsToModel.setReadOnly(True)
        self.le_numberPointsToModel.setObjectName("le_numberPointsToModel")
        self.label_59 = QtWidgets.QLabel(HemisphereDialog)
        self.label_59.setGeometry(QtCore.QRect(335, 30, 96, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.label_149 = QtWidgets.QLabel(HemisphereDialog)
        self.label_149.setGeometry(QtCore.QRect(335, 5, 126, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_149.setFont(font)
        self.label_149.setObjectName("label_149")
        self.line_78 = QtWidgets.QFrame(HemisphereDialog)
        self.line_78.setGeometry(QtCore.QRect(335, 25, 121, 1))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_78.setFont(font)
        self.line_78.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_78.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_78.setObjectName("line_78")
        self.hemisphereBackground.raise_()
        self.hemisphere.raise_()
        self.btn_deletePoints.raise_()
        self.groupBox_2.raise_()
        self.bar_numberPointsProcessed.raise_()
        self.le_numberPointsProcessed.raise_()
        self.label_81.raise_()
        self.bar_numberPointsSolved.raise_()
        self.le_numberPointsSolved.raise_()
        self.label_28.raise_()
        self.bar_numberPointsImaged.raise_()
        self.le_numberPointsImaged.raise_()
        self.label_77.raise_()
        self.bar_numberPointsSlewed.raise_()
        self.le_numberPointsSlewed.raise_()
        self.label_100.raise_()
        self.le_numberPointsToModel.raise_()
        self.label_59.raise_()
        self.label_149.raise_()
        self.line_78.raise_()

        self.retranslateUi(HemisphereDialog)
        QtCore.QMetaObject.connectSlotsByName(HemisphereDialog)

    def retranslateUi(self, HemisphereDialog):
        _translate = QtCore.QCoreApplication.translate
        HemisphereDialog.setWindowTitle(_translate("HemisphereDialog", "Hemisphere"))
        self.btn_deletePoints.setToolTip(_translate("HemisphereDialog", "<html><head/><body><p>Delete all points on coordinate window including Base / Model</p></body></html>"))
        self.btn_deletePoints.setText(_translate("HemisphereDialog", "Clear\n"
"Model Points"))
        self.groupBox_2.setTitle(_translate("HemisphereDialog", "Edit"))
        self.btn_editNone.setText(_translate("HemisphereDialog", "Nothing"))
        self.btn_editModelPoints.setText(_translate("HemisphereDialog", "Model Points"))
        self.btn_editHorizonMask.setText(_translate("HemisphereDialog", "Horizon Mask"))
        self.le_numberPointsProcessed.setToolTip(_translate("HemisphereDialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Progress in modeling.</span></p></body></html>"))
        self.le_numberPointsProcessed.setText(_translate("HemisphereDialog", "00"))
        self.label_81.setText(_translate("HemisphereDialog", "Processed:"))
        self.le_numberPointsSolved.setToolTip(_translate("HemisphereDialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Progress in modeling.</span></p></body></html>"))
        self.le_numberPointsSolved.setText(_translate("HemisphereDialog", "00"))
        self.label_28.setText(_translate("HemisphereDialog", "Solved:"))
        self.le_numberPointsImaged.setToolTip(_translate("HemisphereDialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Progress in modeling.</span></p></body></html>"))
        self.le_numberPointsImaged.setText(_translate("HemisphereDialog", "00"))
        self.label_77.setText(_translate("HemisphereDialog", "Imaged:"))
        self.le_numberPointsSlewed.setToolTip(_translate("HemisphereDialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Progress in modeling.</span></p></body></html>"))
        self.le_numberPointsSlewed.setText(_translate("HemisphereDialog", "00"))
        self.label_100.setText(_translate("HemisphereDialog", "Slewed:"))
        self.le_numberPointsToModel.setToolTip(_translate("HemisphereDialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Progress in modeling.</span></p></body></html>"))
        self.le_numberPointsToModel.setText(_translate("HemisphereDialog", "00"))
        self.label_59.setText(_translate("HemisphereDialog", "Points to model:"))
        self.label_149.setText(_translate("HemisphereDialog", "Modeling progress"))

