# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'satellite_window_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SatelliteDialog(object):
    def setupUi(self, SatelliteDialog):
        SatelliteDialog.setObjectName("SatelliteDialog")
        SatelliteDialog.resize(791, 641)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SatelliteDialog.sizePolicy().hasHeightForWidth())
        SatelliteDialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        SatelliteDialog.setFont(font)
        self.satellite = QtWidgets.QWidget(SatelliteDialog)
        self.satellite.setEnabled(True)
        self.satellite.setGeometry(QtCore.QRect(10, 130, 771, 501))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.satellite.sizePolicy().hasHeightForWidth())
        self.satellite.setSizePolicy(sizePolicy)
        self.satellite.setSizeIncrement(QtCore.QSize(0, 10))
        self.satellite.setAutoFillBackground(True)
        self.satellite.setStyleSheet("")
        self.satellite.setObjectName("satellite")
        self.btn_calculateValues = QtWidgets.QPushButton(SatelliteDialog)
        self.btn_calculateValues.setGeometry(QtCore.QRect(25, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_calculateValues.setFont(font)
        self.btn_calculateValues.setObjectName("btn_calculateValues")
        self.satelliteBackground = QtWidgets.QLabel(SatelliteDialog)
        self.satelliteBackground.setGeometry(QtCore.QRect(0, 0, 791, 126))
        self.satelliteBackground.setText("")
        self.satelliteBackground.setObjectName("satelliteBackground")
        self.satelliteMoving = QtWidgets.QWidget(SatelliteDialog)
        self.satelliteMoving.setEnabled(True)
        self.satelliteMoving.setGeometry(QtCore.QRect(10, 130, 771, 501))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.satelliteMoving.sizePolicy().hasHeightForWidth())
        self.satelliteMoving.setSizePolicy(sizePolicy)
        self.satelliteMoving.setAutoFillBackground(False)
        self.satelliteMoving.setStyleSheet("")
        self.satelliteMoving.setObjectName("satelliteMoving")
        self.label_242 = QtWidgets.QLabel(SatelliteDialog)
        self.label_242.setGeometry(QtCore.QRect(160, 20, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_242.setFont(font)
        self.label_242.setObjectName("label_242")
        self.le_satelliteAlt = QtWidgets.QLineEdit(SatelliteDialog)
        self.le_satelliteAlt.setEnabled(True)
        self.le_satelliteAlt.setGeometry(QtCore.QRect(210, 20, 66, 21))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.le_satelliteAlt.setFont(font)
        self.le_satelliteAlt.setMouseTracking(False)
        self.le_satelliteAlt.setAcceptDrops(False)
        self.le_satelliteAlt.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.le_satelliteAlt.setText("")
        self.le_satelliteAlt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_satelliteAlt.setReadOnly(False)
        self.le_satelliteAlt.setObjectName("le_satelliteAlt")
        self.le_satellitePassStart = QtWidgets.QLineEdit(SatelliteDialog)
        self.le_satellitePassStart.setEnabled(True)
        self.le_satellitePassStart.setGeometry(QtCore.QRect(370, 20, 66, 21))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.le_satellitePassStart.setFont(font)
        self.le_satellitePassStart.setMouseTracking(False)
        self.le_satellitePassStart.setAcceptDrops(False)
        self.le_satellitePassStart.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.le_satellitePassStart.setText("")
        self.le_satellitePassStart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_satellitePassStart.setReadOnly(False)
        self.le_satellitePassStart.setObjectName("le_satellitePassStart")
        self.label_244 = QtWidgets.QLabel(SatelliteDialog)
        self.label_244.setGeometry(QtCore.QRect(295, 20, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_244.setFont(font)
        self.label_244.setObjectName("label_244")
        self.le_satellitePassEnd = QtWidgets.QLineEdit(SatelliteDialog)
        self.le_satellitePassEnd.setEnabled(True)
        self.le_satellitePassEnd.setGeometry(QtCore.QRect(370, 45, 66, 21))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.le_satellitePassEnd.setFont(font)
        self.le_satellitePassEnd.setMouseTracking(False)
        self.le_satellitePassEnd.setAcceptDrops(False)
        self.le_satellitePassEnd.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.le_satellitePassEnd.setText("")
        self.le_satellitePassEnd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_satellitePassEnd.setReadOnly(False)
        self.le_satellitePassEnd.setObjectName("le_satellitePassEnd")
        self.label_243 = QtWidgets.QLabel(SatelliteDialog)
        self.label_243.setGeometry(QtCore.QRect(160, 45, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_243.setFont(font)
        self.label_243.setObjectName("label_243")
        self.label_245 = QtWidgets.QLabel(SatelliteDialog)
        self.label_245.setGeometry(QtCore.QRect(295, 45, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_245.setFont(font)
        self.label_245.setObjectName("label_245")
        self.le_satelliteAz = QtWidgets.QLineEdit(SatelliteDialog)
        self.le_satelliteAz.setEnabled(True)
        self.le_satelliteAz.setGeometry(QtCore.QRect(210, 45, 66, 21))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.le_satelliteAz.setFont(font)
        self.le_satelliteAz.setMouseTracking(False)
        self.le_satelliteAz.setAcceptDrops(False)
        self.le_satelliteAz.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.le_satelliteAz.setText("")
        self.le_satelliteAz.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_satelliteAz.setReadOnly(False)
        self.le_satelliteAz.setObjectName("le_satelliteAz")
        self.satelliteBackground.raise_()
        self.btn_calculateValues.raise_()
        self.satellite.raise_()
        self.satelliteMoving.raise_()
        self.label_242.raise_()
        self.le_satelliteAlt.raise_()
        self.le_satellitePassStart.raise_()
        self.label_244.raise_()
        self.le_satellitePassEnd.raise_()
        self.label_243.raise_()
        self.label_245.raise_()
        self.le_satelliteAz.raise_()

        self.retranslateUi(SatelliteDialog)
        QtCore.QMetaObject.connectSlotsByName(SatelliteDialog)

    def retranslateUi(self, SatelliteDialog):
        _translate = QtCore.QCoreApplication.translate
        SatelliteDialog.setWindowTitle(_translate("SatelliteDialog", "Satellite"))
        self.btn_calculateValues.setToolTip(_translate("SatelliteDialog", "<html><head/><body><p>Delete all points on coordinate window including Base / Model</p></body></html>"))
        self.btn_calculateValues.setText(_translate("SatelliteDialog", "Calculate"))
        self.satelliteBackground.setProperty("color", _translate("SatelliteDialog", "blue"))
        self.label_242.setText(_translate("SatelliteDialog", "Alt now"))
        self.le_satelliteAlt.setToolTip(_translate("SatelliteDialog", "<html><head/><body><p>Name of Horizon Mask file, where the data is stored.</p><p>Please Double Click to Select.</p></body></html>"))
        self.le_satellitePassStart.setToolTip(_translate("SatelliteDialog", "<html><head/><body><p>Name of Horizon Mask file, where the data is stored.</p><p>Please Double Click to Select.</p></body></html>"))
        self.label_244.setText(_translate("SatelliteDialog", "Pass Start"))
        self.le_satellitePassEnd.setToolTip(_translate("SatelliteDialog", "<html><head/><body><p>Name of Horizon Mask file, where the data is stored.</p><p>Please Double Click to Select.</p></body></html>"))
        self.label_243.setText(_translate("SatelliteDialog", "Az now"))
        self.label_245.setText(_translate("SatelliteDialog", "Pass End"))
        self.le_satelliteAz.setToolTip(_translate("SatelliteDialog", "<html><head/><body><p>Name of Horizon Mask file, where the data is stored.</p><p>Please Double Click to Select.</p></body></html>"))

