@startuml

scale max 1536 width
hide stereotype

node "mountwizzard" {
    [Mount Wizzard App]
}

package "mount" {
    [mount_thread] --> [ipdirect] : use
    [mount_thread] --> [ascommount] : use
}

package "astrometry" {
    [transform]
}

package "modeling" {
    [modeling_thread]
}

package "environment" {
    [stick_thread]
    [unihedron_thread]
    [weather_thread]
}

package "camera" {
    [none]
    [ascomcam]
    [maximdl]
    [sgpro]
    [theskyx]
}

package "analyse" {
    [analysedata]
}

package "dome" {
    [dome_thread]
}

package "relays" {
    [relays_]
}

package "remote" {
    [remote_thread]
}

[Mount Wizzard App] -> [mount_thread] : use
[Mount Wizzard App] -> [stick_thread] : use
[Mount Wizzard App] -> [weather_thread] : use
[Mount Wizzard App] -> [unihedron_thread] : use
[Mount Wizzard App] -> [modeling_thread] : use
[Mount Wizzard App] -> [remote_thread] : use
[Mount Wizzard App] -> [dome_thread] : use
[Mount Wizzard App] -> [relays_] : use
[Mount Wizzard App] --> [analysedata] : use

[mount_thread] --> [transform]

[modeling_thread] --> [none] : use
[modeling_thread] --> [ascomcam] : use
[modeling_thread] --> [maximdl] : use
[modeling_thread] --> [sgpro] : use
[modeling_thread] --> [theskyx] : use



@enduml