@startuml

class Camera {
cameraStatus = list['Not Connected','Connected','Integrating','Downloading','IDLE','Error']
int binX
int binY
bool canSubframe
int numX
int numY

int
connect()
disconnect()
getStatus()
_getProps()
downloadImage()
expose()
abortExposure()
setup()
}

@enduml