# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'image_dialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ImageDialog(object):
    def setupUi(self, ImageDialog):
        ImageDialog.setObjectName("ImageDialog")
        ImageDialog.resize(790, 670)
        self.windowTitle = QtWidgets.QLabel(ImageDialog)
        self.windowTitle.setGeometry(QtCore.QRect(0, 0, 791, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.windowTitle.setFont(font)
        self.windowTitle.setAutoFillBackground(True)
        self.windowTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.windowTitle.setObjectName("windowTitle")
        self.image = QtWidgets.QWidget(ImageDialog)
        self.image.setGeometry(QtCore.QRect(0, 100, 791, 571))
        self.image.setObjectName("image")
        self.btn_expose = QtWidgets.QPushButton(ImageDialog)
        self.btn_expose.setGeometry(QtCore.QRect(10, 50, 81, 31))
        self.btn_expose.setObjectName("btn_expose")
        self.checkFastDownload = QtWidgets.QCheckBox(ImageDialog)
        self.checkFastDownload.setGeometry(QtCore.QRect(100, 70, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkFastDownload.setFont(font)
        self.checkFastDownload.setChecked(True)
        self.checkFastDownload.setObjectName("checkFastDownload")
        self.cameraExposure = QtWidgets.QSpinBox(ImageDialog)
        self.cameraExposure.setGeometry(QtCore.QRect(150, 40, 41, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cameraExposure.setFont(font)
        self.cameraExposure.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.cameraExposure.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cameraExposure.setMinimum(1)
        self.cameraExposure.setMaximum(10)
        self.cameraExposure.setProperty("value", 1)
        self.cameraExposure.setObjectName("cameraExposure")
        self.label_39 = QtWidgets.QLabel(ImageDialog)
        self.label_39.setGeometry(QtCore.QRect(100, 40, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.label_165 = QtWidgets.QLabel(ImageDialog)
        self.label_165.setGeometry(QtCore.QRect(200, 40, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_165.setFont(font)
        self.label_165.setObjectName("label_165")
        self.btn_size25 = QtWidgets.QPushButton(ImageDialog)
        self.btn_size25.setGeometry(QtCore.QRect(240, 50, 81, 31))
        self.btn_size25.setObjectName("btn_size25")
        self.btn_size50 = QtWidgets.QPushButton(ImageDialog)
        self.btn_size50.setGeometry(QtCore.QRect(330, 50, 81, 31))
        self.btn_size50.setObjectName("btn_size50")
        self.btn_size100 = QtWidgets.QPushButton(ImageDialog)
        self.btn_size100.setGeometry(QtCore.QRect(420, 50, 81, 31))
        self.btn_size100.setObjectName("btn_size100")
        self.btn_connectCamPS = QtWidgets.QPushButton(ImageDialog)
        self.btn_connectCamPS.setGeometry(QtCore.QRect(610, 50, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_connectCamPS.setFont(font)
        self.btn_connectCamPS.setObjectName("btn_connectCamPS")
        self.btn_disconnectCamPS = QtWidgets.QPushButton(ImageDialog)
        self.btn_disconnectCamPS.setGeometry(QtCore.QRect(700, 50, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_disconnectCamPS.setFont(font)
        self.btn_disconnectCamPS.setObjectName("btn_disconnectCamPS")

        self.retranslateUi(ImageDialog)
        QtCore.QMetaObject.connectSlotsByName(ImageDialog)

    def retranslateUi(self, ImageDialog):
        _translate = QtCore.QCoreApplication.translate
        ImageDialog.setWindowTitle(_translate("ImageDialog", "Form"))
        self.windowTitle.setText(_translate("ImageDialog", "Image"))
        self.btn_expose.setToolTip(_translate("ImageDialog", "Saves actual model und name \"SIMPLE\" in mount"))
        self.btn_expose.setText(_translate("ImageDialog", "Expose"))
        self.checkFastDownload.setToolTip(_translate("ImageDialog", "Use Highspeed download of CCD camera if availabe"))
        self.checkFastDownload.setText(_translate("ImageDialog", "Fast Download"))
        self.cameraExposure.setToolTip(_translate("ImageDialog", "sets the exposure time"))
        self.label_39.setText(_translate("ImageDialog", "Length"))
        self.label_165.setText(_translate("ImageDialog", "s"))
        self.btn_size25.setToolTip(_translate("ImageDialog", "Saves actual model und name \"SIMPLE\" in mount"))
        self.btn_size25.setText(_translate("ImageDialog", "25%"))
        self.btn_size50.setToolTip(_translate("ImageDialog", "Saves actual model und name \"SIMPLE\" in mount"))
        self.btn_size50.setText(_translate("ImageDialog", "50%"))
        self.btn_size100.setToolTip(_translate("ImageDialog", "Saves actual model und name \"SIMPLE\" in mount"))
        self.btn_size100.setText(_translate("ImageDialog", "100%"))
        self.btn_connectCamPS.setText(_translate("ImageDialog", "Connect"))
        self.btn_disconnectCamPS.setText(_translate("ImageDialog", "Disconnect"))

